### ISSUE TITLE
Add to List link displays above mega menu

### ISSUE THREAD

**Issue by CristinaSolana** [envistaInteractive/itagroup-ecommerce-template#100]
### Summary
.add-to-list on product detail page has a z-index of 10 which is not necessary. That z-index causes it to be display above the mega menu. Remove and test to make sure it still appears over images.

![screen shot 2017-08-15 at 12 24 20 pm](https://user-images.githubusercontent.com/524896/29325269-1186dcde-81b5-11e7-8ffc-b216a3037bc8.png)

**Comment by cperez08** [comment]
PR Merged, should be done
