### ISSUE TITLE
I-Phone Flex-box Safari issues

### ISSUE THREAD

**Issue by itsDiwaker** [envistaInteractive/itagroup-ecommerce-template#227]
Hi @CristinaSolana, 
While testing on browser stack, I observed that the layout is completely distorted. As I-Phone 6 and lower versions do not support standard flex properties.

Integrating `gulp-autoprefixer` to `node-ecom-web's` `gulp.babel.js` file solves a lot of issues. But not all.
https://github.com/sindresorhus/gulp-autoprefixer

Creating this ticket so that we have it on our radar.

<img width="389" alt="screen shot 2017-09-15 at 3 59 12 pm" src="https://user-images.githubusercontent.com/10872098/30479977-2a57d658-9a35-11e7-94c5-b1cd1da2585b.png">

**Comment by CristinaSolana** [comment]
@itsDiwaker Yes, let's implement autoprefixer. That was actually my fault, that was the plan and just went off my radar.
