### ISSUE TITLE
Card Module (callout)

### ISSUE THREAD

**Issue by CristinaSolana** [envistaInteractive/itagroup-ecommerce-template#26]
### Summary
Block with various modifiers for padding, background-color, box-shadow, border, etc. Should be able to use http://foundation.zurb.com/sites/docs/callout.html as a foundation.

##### Notes
Please review Sketch files for mobile and desktop layouts 

### Example
![screen shot 2017-07-24 at 10 37 02 am](https://user-images.githubusercontent.com/524896/28536305-319908cc-7075-11e7-9f9b-4066295380f2.png)
![screen shot 2017-07-31 at 3 14 35 pm](https://user-images.githubusercontent.com/524896/28794109-363e403e-7603-11e7-8c8c-3956e24f9f2c.png)
![screen shot 2017-07-31 at 3 14 40 pm](https://user-images.githubusercontent.com/524896/28794108-363cea72-7603-11e7-99fc-30e7564613e3.png)

**Comment by zetogk** [comment]
Current status:
- The cards for payment methods and addresses are ready.
- Is missing the assets for credit cards in payment methods and the image for border-bottom for 'your order summary'.

**Comment by CristinaSolana** [comment]
@zetogk The credit cards assets are context specific so they do not need to be part of the module, it is only the styling of the card itself that is needed. I will request the image for the bottom border of the receipt style card and provide it once available.

**Comment by CristinaSolana** [comment]
@zetogk below are images, one with the other without shadow.

![receipt-bottom-shadow](https://user-images.githubusercontent.com/524896/29215485-26867fc0-7e79-11e7-8ba5-e3ac09d16ebf.png)
![receipt-bottom](https://user-images.githubusercontent.com/524896/29215486-2687f74c-7e79-11e7-847b-b5eacf7392ab.png)

**Comment by zetogk** [comment]
Thank you, I will add the shadow.

**Comment by zetogk** [comment]
@CristinaSolana 

In the last commit, I updated the markup of example for 'your-order-summary'. In the example, the images used in CSS are not loaded in the documentation. (For example: background: url('..'))
