### ISSUE TITLE
Validate shipping address

### ISSUE THREAD

**Issue by CristinaSolana** [envistaInteractive/itagroup-ecommerce-template#340]
### Summary
Validate shipping and billing address before setting or saving.

If there is 1 or more totalRecords returned, the records should be displayed to the user in a modal with the ability to select the address they originally entered or select from the list of "recommended addresses" (records). The endpoint returns an object with a "records" array. Currently the totalRecords field returns a string so the value should be parseInt before evaluating condition. When an address has been selected, user should be given option to save address to customer addresses. Limit the recommended addresses to first 4 records.

![validate address](https://user-images.githubusercontent.com/524896/32178104-4c10214c-bd62-11e7-9eaa-05403322a795.png)

This validation is not necessary for saved addresses as they will have already been validated before saving.

We will start with US addresses as the first iteration as there will be complexities to plan around address forms for other countries that might require other fields).

**Endpoint**: `/api/profile/addresses/validate`
**Payload**
```
{
    t: 'TransmissionReference', // optional
    org: 'Organization', // optional
    a1: '4550 sw 163 Path',
    a2: 'apt #2', // optional
    loc: 'Miami',
    AdministrativeArea: 'FL',
    postal: '33185',
    ctry: 'US',
    format: 'JSON'
}
```

**Comment by itsDiwaker** [comment]
_Feedback to work on:_

- Too much space under titles: "Save the correct address" and "or Select a recommended address". Make bottom margins smaller
- Change modal title to "Choose an address" and remove margin from top
- Make "or Select a recommended address" smaller font size than the modal title
- Address blocks under "or Select a recommended address" not aligned to begin same as the use my address
- Addresses under "or Select a recommended address" have the city, state and zip twice (seems like it is added as line 2 of the address

**Comment by itsDiwaker** [comment]
@CristinaSolana 

> Addresses under "or Select a recommended address" have the city, state and zip twice (seems like it is added as line 2 of the address

**Reply:** It's API that is returning state and city as part of `addressLine1` property. 
<img width="404" alt="screen shot 2017-11-03 at 5 33 26 pm" src="https://user-images.githubusercontent.com/10872098/32373073-7aba537e-c0bd-11e7-8192-e935691c81b8.png">
