### ISSUE TITLE
Cart Page

### ISSUE THREAD

**Issue by CristinaSolana** [envistaInteractive/itagroup-ecommerce-template#68]
### Summary
Layout contents of Cart Page as specified on Cart Page in Zeplin. 

Use a mobile first approach to adjust the layout using responsive design as the screen gets larger.

**Create branch**: feature/cart
**Layout file**: templates/cart.liquid
**Url for testing**: http://localhost:1337/cart
**Delivery Date**: August 17th

![screen shot 2017-08-08 at 12 21 41 pm](https://user-images.githubusercontent.com/524896/29082759-79557982-7c34-11e7-93d4-25ee93a864ef.png)

**Comment by cperez08** [comment]
@zetogk pls give priority to this issue.

**Comment by zetogk** [comment]
Before to check it issue, is necessary having the card module.
